// <auto-generated />
using System;
using AmigoOculto.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmigoOculto.Repository.Migrations
{
    [DbContext(typeof(AmigoOcultoContext))]
    partial class AmigoOcultoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bdAmigoOculto")
                .HasAnnotation("ProductVersion", "3.0.0-preview.18572.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmigoOculto.Domain.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataHoraEntrega")
                        .HasColumnName("DataHoraEntrega");

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao");

                    b.Property<string>("Localizacao")
                        .HasColumnName("Localizacao");

                    b.Property<string>("Observacao")
                        .HasColumnName("Observacao");

                    b.HasKey("Id")
                        .HasName("Pk_Grupo");

                    b.ToTable("tb_grupo");
                });

            modelBuilder.Entity("AmigoOculto.Domain.Models.GrupoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmigoId");

                    b.Property<int>("GrupoId");

                    b.HasKey("Id")
                        .HasName("Pk_GrupoUsuario");

                    b.HasIndex("AmigoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("tb_grupousuario");
                });

            modelBuilder.Entity("AmigoOculto.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Detalhes")
                        .HasColumnName("Detalhes");

                    b.Property<string>("Email")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(200);

                    b.Property<string>("Telefone")
                        .HasColumnName("Telefone");

                    b.HasKey("Id")
                        .HasName("Pk_Usuario");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("AmigoOculto.Domain.Models.GrupoUsuario", b =>
                {
                    b.HasOne("AmigoOculto.Domain.Models.Usuario", "Usuario")
                        .WithMany("GrupoUsuarios")
                        .HasForeignKey("AmigoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AmigoOculto.Domain.Models.Grupo", "Grupo")
                        .WithMany("Participantes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
